# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CmdMessage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CmdMessage.proto',
  package='',
  serialized_pb='\n\x10\x43mdMessage.proto\"\x1b\n\x19Request_Get_LoginGateInfo\"B\n\x17RePly_Get_LoginGateInfo\x12\r\n\x05\x65rror\x18\x01 \x02(\r\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\r\"(\n\x17Reply_Connect_Logingate\x12\r\n\x05\x65rror\x18\x01 \x02(\r\":\n\rRequest_Login\x12\x14\n\x0c\x61\x63\x63ount_name\x18\x01 \x02(\t\x12\x13\n\x0b\x61\x63\x63ount_pwd\x18\x02 \x02(\t\"?\n\x0bReply_Login\x12\r\n\x05\x65rror\x18\x01 \x02(\r\x12\x12\n\naccount_id\x18\x02 \x01(\r\x12\r\n\x05token\x18\x03 \x01(\t\";\n\x16Request_Get_GameCenter\x12\x12\n\naccount_id\x18\x01 \x02(\r\x12\r\n\x05token\x18\x02 \x02(\t\"U\n\x14Reply_Get_GameCenter\x12\r\n\x05\x65rror\x18\x01 \x02(\r\x12\x15\n\rgamecenter_ip\x18\x02 \x01(\t\x12\x17\n\x0fgamecenter_port\x18\x03 \x01(\r\"=\n\x18Request_Enter_GameCenter\x12\x12\n\naccount_id\x18\x01 \x02(\r\x12\r\n\x05token\x18\x02 \x02(\t\"Z\n\x16RePly_Enter_GameCenter\x12\r\n\x05\x65rror\x18\x01 \x02(\r\x12\x0f\n\x07user_id\x18\x02 \x01(\r\x12\x11\n\tuser_name\x18\x03 \x01(\t\x12\r\n\x05money\x18\x04 \x01(\r')




_REQUEST_GET_LOGINGATEINFO = _descriptor.Descriptor(
  name='Request_Get_LoginGateInfo',
  full_name='Request_Get_LoginGateInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=20,
  serialized_end=47,
)


_REPLY_GET_LOGINGATEINFO = _descriptor.Descriptor(
  name='RePly_Get_LoginGateInfo',
  full_name='RePly_Get_LoginGateInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='RePly_Get_LoginGateInfo.error', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ip', full_name='RePly_Get_LoginGateInfo.ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='RePly_Get_LoginGateInfo.port', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=49,
  serialized_end=115,
)


_REPLY_CONNECT_LOGINGATE = _descriptor.Descriptor(
  name='Reply_Connect_Logingate',
  full_name='Reply_Connect_Logingate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='Reply_Connect_Logingate.error', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=117,
  serialized_end=157,
)


_REQUEST_LOGIN = _descriptor.Descriptor(
  name='Request_Login',
  full_name='Request_Login',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_name', full_name='Request_Login.account_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='account_pwd', full_name='Request_Login.account_pwd', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=159,
  serialized_end=217,
)


_REPLY_LOGIN = _descriptor.Descriptor(
  name='Reply_Login',
  full_name='Reply_Login',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='Reply_Login.error', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='account_id', full_name='Reply_Login.account_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='Reply_Login.token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=219,
  serialized_end=282,
)


_REQUEST_GET_GAMECENTER = _descriptor.Descriptor(
  name='Request_Get_GameCenter',
  full_name='Request_Get_GameCenter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='Request_Get_GameCenter.account_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='Request_Get_GameCenter.token', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=284,
  serialized_end=343,
)


_REPLY_GET_GAMECENTER = _descriptor.Descriptor(
  name='Reply_Get_GameCenter',
  full_name='Reply_Get_GameCenter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='Reply_Get_GameCenter.error', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gamecenter_ip', full_name='Reply_Get_GameCenter.gamecenter_ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gamecenter_port', full_name='Reply_Get_GameCenter.gamecenter_port', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=345,
  serialized_end=430,
)


_REQUEST_ENTER_GAMECENTER = _descriptor.Descriptor(
  name='Request_Enter_GameCenter',
  full_name='Request_Enter_GameCenter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='Request_Enter_GameCenter.account_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='Request_Enter_GameCenter.token', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=432,
  serialized_end=493,
)


_REPLY_ENTER_GAMECENTER = _descriptor.Descriptor(
  name='RePly_Enter_GameCenter',
  full_name='RePly_Enter_GameCenter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='RePly_Enter_GameCenter.error', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='RePly_Enter_GameCenter.user_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_name', full_name='RePly_Enter_GameCenter.user_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='money', full_name='RePly_Enter_GameCenter.money', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=495,
  serialized_end=585,
)

DESCRIPTOR.message_types_by_name['Request_Get_LoginGateInfo'] = _REQUEST_GET_LOGINGATEINFO
DESCRIPTOR.message_types_by_name['RePly_Get_LoginGateInfo'] = _REPLY_GET_LOGINGATEINFO
DESCRIPTOR.message_types_by_name['Reply_Connect_Logingate'] = _REPLY_CONNECT_LOGINGATE
DESCRIPTOR.message_types_by_name['Request_Login'] = _REQUEST_LOGIN
DESCRIPTOR.message_types_by_name['Reply_Login'] = _REPLY_LOGIN
DESCRIPTOR.message_types_by_name['Request_Get_GameCenter'] = _REQUEST_GET_GAMECENTER
DESCRIPTOR.message_types_by_name['Reply_Get_GameCenter'] = _REPLY_GET_GAMECENTER
DESCRIPTOR.message_types_by_name['Request_Enter_GameCenter'] = _REQUEST_ENTER_GAMECENTER
DESCRIPTOR.message_types_by_name['RePly_Enter_GameCenter'] = _REPLY_ENTER_GAMECENTER

class Request_Get_LoginGateInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_GET_LOGINGATEINFO

  # @@protoc_insertion_point(class_scope:Request_Get_LoginGateInfo)

class RePly_Get_LoginGateInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REPLY_GET_LOGINGATEINFO

  # @@protoc_insertion_point(class_scope:RePly_Get_LoginGateInfo)

class Reply_Connect_Logingate(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REPLY_CONNECT_LOGINGATE

  # @@protoc_insertion_point(class_scope:Reply_Connect_Logingate)

class Request_Login(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_LOGIN

  # @@protoc_insertion_point(class_scope:Request_Login)

class Reply_Login(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REPLY_LOGIN

  # @@protoc_insertion_point(class_scope:Reply_Login)

class Request_Get_GameCenter(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_GET_GAMECENTER

  # @@protoc_insertion_point(class_scope:Request_Get_GameCenter)

class Reply_Get_GameCenter(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REPLY_GET_GAMECENTER

  # @@protoc_insertion_point(class_scope:Reply_Get_GameCenter)

class Request_Enter_GameCenter(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_ENTER_GAMECENTER

  # @@protoc_insertion_point(class_scope:Request_Enter_GameCenter)

class RePly_Enter_GameCenter(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REPLY_ENTER_GAMECENTER

  # @@protoc_insertion_point(class_scope:RePly_Enter_GameCenter)


# @@protoc_insertion_point(module_scope)
