# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Common.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Common.proto',
  package='',
  serialized_pb='\n\x0c\x43ommon.proto\"I\n\x10struct_game_info\x12\x11\n\tgame_type\x18\x01 \x02(\r\x12\x0f\n\x07game_ip\x18\x02 \x01(\t\x12\x11\n\tgame_port\x18\x03 \x01(\r')




_STRUCT_GAME_INFO = _descriptor.Descriptor(
  name='struct_game_info',
  full_name='struct_game_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='game_type', full_name='struct_game_info.game_type', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='game_ip', full_name='struct_game_info.game_ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='game_port', full_name='struct_game_info.game_port', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=16,
  serialized_end=89,
)

DESCRIPTOR.message_types_by_name['struct_game_info'] = _STRUCT_GAME_INFO

class struct_game_info(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STRUCT_GAME_INFO

  # @@protoc_insertion_point(class_scope:struct_game_info)


# @@protoc_insertion_point(module_scope)
