#coding=utf-8

#=======客户端类型
CLIENT_TYPE_USER=0
CLIENT_TYPE_LOGINGATE=1
CLIENT_TYPE_LOGINSERVER=2

#=======ErrorCode
ERROR_OK=0
ERROR_MAX_LOGINGATE=1

#=======心跳包
KEEPLIVE=1


#=======登录网关服务器到登录网关管理服务器消息ID:[100-200]
L2LGATEM_REQUEST_CONFIG=100

#=======登录网关管理服务器to登录网关服务器消息ID:[200-300]
LGATEM2L_REPLY_CONFIG=200